name: tomcat_deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to tomcat
      run: curl -v -u admin:admin -T /home/runner/work/sureshProject/sureshProject/target/COH.war 'http://52.221.188.237:8080/manager'
